### PR TITLE
Add app in top level config

### PR DESCRIPTION
**Pull request by steventsao**
- updated readme
- updated tests to handle the new config

### CODE REVIEW

**Comment by steventsao** [comment]
Draft that resolves #2.

**Comment by steventsao** [comment]
> What I am really surprised about is that the blueprint test is not failing! It seems you (rightly) changed the default blueprint, but forgot to update the test fixture (https://github.com/kaliber5/ember-cli-bundlesize/blob/master/node-tests/fixtures/config/bundlesize.js). No big deal, but I really don't understand why this was not failing the test!? 🤔

It looks like the test only passed because `emberGenerate` was used [incorrectly](https://github.com/ember-cli/ember-cli-blueprint-test-helpers/blob/e947cdb09c6e2a469c07ef14377e5b15f2acfcb6/lib/ember-generate.js#L14) and the assertion had timed out. The function returns a promise and does not take a callback that returns a `file`. I've moved the assertion to after the promise resolves and to compare their buffers instead. LMK what you think!

**Comment by simonihmig** [comment]
> It looks like the test only passed because emberGenerate was used incorrectly and the assertion had timed out.

Seems you are right, thanks for investigating!

> I've moved the assertion to after the promise resolves and to compare their buffers instead.

I prefer not to compare buffers, but still use the `file` helper for that. As in the [examples](https://github.com/ember-cli/ember-cli-blueprint-test-helpers#example-usage). What's missing in the examples is the part to import the `file` helper, which can be done like [here](https://github.com/kaliber5/ember-bootstrap/blob/master/node-tests/blueprints/ember-bootstrap-test.js#L15-L16). Would you be able to update that accordingly?

**Comment by steventsao** [comment]
Done. the error case looks much better than using buffer.
```
AssertionError: expected "config/bundlesize.js" to equal "/Users/steventsao/workspace/ember-cli-bundlesize/node-tests/blueprints/../fixtures/config/bundlesize.js"
      + expected - actual

       'use strict';

       module.exports = {
      -  app: {
      +  appppppp: {
```

**Comment by simonihmig** [comment]
Published as 0.1.0! :tada:

**Pull request merged**
